services:
  whisper:
    image: rocm-wyoming-whisper
    container_name: whisper
    restart: unless-stopped
    group_add:
      - video
    volumes:
      - whisper-data:/data
    command:
      - --download-dir
      - /data
      - --model
      - medium
      - --device
      - cuda
    ports:
      - 10300:10300
    devices:
      - "/dev/dri"
      - "/dev/kfd"

volumes:
  whisper-data: